defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_
  
scheduler:
  decay_rate: 0.95
  decay_steps: 500

training:
  rec_validation_freq: 100
  rec_inference_freq: 100
  rec_monitor_freq: 100
  rec_constraint_freq: 100
  max_steps : 10000

batch_size:
  Interior: 4096
  IC: 2048
  BC: 2048

custom:
  beta: 1.0
  model_type: "FourierNetArch" # allowerd: FourierNetArch, ModifiedFourierNetArch, SirenArch, FullyConnectedArch

graph:
  func_arch: true

network_dir: "plain_beta1"
initialization_network_dir: ""
